/** 内置头像图库（public/img），构建时静态枚举 */
export const BUILTIN_AVATARS: { path: string; label: string }[] = [
  { path: '/img/qwen.jpg', label: '千问' },
  { path: '/img/doubao_new.png', label: '豆包' },
  { path: '/img/yuanbao.png', label: '元宝' },
  { path: '/img/ds.svg', label: 'DeepSeek' },
  { path: '/img/glm.gif', label: '智谱' },
  { path: '/img/kimi.jpg', label: 'Kimi' },
  { path: '/img/baidu.svg', label: '文心' },
  { path: '/img/spymaster.jpg', label: '主持人' },
  { path: '/img/codex.webp', label: 'Codex' },
  { path: '/img/claude.webp', label: 'Claude' },
  { path: '/img/opencode.webp', label: 'OpenCode' },
  { path: '/img/douba.jpeg', label: '豆爸' },
  { path: '/img/douma.jpeg', label: '豆妈' },
  { path: '/img/doujie.jpeg', label: '豆姐' },
  { path: '/img/doumei.jpeg', label: '豆妹' },
  { path: '/img/douhai.jpeg', label: '豆孩' },
  { path: '/img/dousha.jpeg', label: '豆沙' },
  { path: '/img/dounai.jpeg', label: '豆奶' },
  { path: '/img/douye.jpeg', label: '豆爷' },
  { path: '/img/bigmodel.png', label: 'BigModel' },
  { path: '/img/logo.svg', label: 'Logo' },
];
